#!/usr/bin/env bash
# Installs NGINX on new machine listening on port 80
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
