#!/usr/bin/env bash
# Installs NGINX on new machine listening on port 80
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
var1="error_page 404 /404.html; \nlocation = /404.html {\nroot /usr/share/nginx/html;\ninternal;\n}"
var2="location /redirect_me {rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4$1 permanent;}"
sed -i "30i $var2" /etc/nginx/sites-available/default
sed -i "40i $var1" /etc/nginx/sites-available/default
service nginx restart
